/**
 * Zod schemas for the hybrid pipeline (Unit 1 of 8)
 * Defines DocumentMetadata and ProductExtraction schemas for AI-assisted ingestion
 *
 * These schemas are used to:
 * 1. Validate AI model responses with Zod
 * 2. Convert to JSON Schema for Gemini's structured output
 * 3. Provide TypeScript types for type-safe code
 */

import { z } from "zod";
import { zodToJsonSchema } from "zod-to-json-schema";

// ============================================================================
// Page-Level Metadata
// ============================================================================

/**
 * Metadata for a single page in the document
 * Describes layout, content type, and AI interpretation hints
 */
export const PageMetadataSchema = z.object({
  pageNumber: z.number().int().min(1).describe("Page number in the document (1-indexed)"),
  layoutType: z
    .enum([
      "table",
      "list",
      "mixed",
      "full-page-image",
      "title-page",
      "empty",
      "unrecognized",
    ])
    .describe("Layout type detected on this page"),
  suggestedCategory: z
    .string()
    .optional()
    .describe("Suggested product category based on page content (e.g., 'lacteos', 'carnes')"),
  columns: z
    .array(z.string())
    .optional()
    .describe("Column headers detected in tables (e.g., ['nombre', 'marca', 'precio'])"),
  tables: z
    .array(
      z.object({
        rowCount: z.number().int().nonnegative().describe("Number of data rows in this table"),
        hasHeader: z.boolean().describe("Whether table has a header row"),
        confidence: z.number().min(0).max(1).describe("Detection confidence (0-1)"),
      })
    )
    .optional()
    .describe("Tables detected on this page with metadata"),
  interpretationRules: z
    .array(z.string())
    .optional()
    .describe("Special rules for interpreting this page (e.g., 'prices in column 3 include VAT')"),
});

export type PageMetadata = z.infer<typeof PageMetadataSchema>;

// ============================================================================
// Section Metadata
// ============================================================================

/**
 * Metadata for a document section (may span multiple pages)
 * Sections represent logical groupings like categories or chapters
 */
export const SectionMetadataSchema = z.object({
  title: z.string().describe("Section title (e.g., 'BEBIDAS', 'LACTEOS')"),
  startPage: z.number().int().min(1).describe("First page number of this section"),
  endPage: z.number().int().min(1).describe("Last page number of this section"),
  category: z.string().optional().describe("Product category for this section"),
  notes: z.string().optional().describe("Additional notes about this section"),
});

export type SectionMetadata = z.infer<typeof SectionMetadataSchema>;

// ============================================================================
// Document Metadata
// ============================================================================

/**
 * Global metadata for the entire document
 * Generated by a high-capacity model and reused across chunk processing
 */
export const DocumentMetadataSchema = z.object({
  documentType: z
    .enum(["price-list", "catalog", "invoice", "order-form", "unknown"])
    .describe("Type of document detected"),
  language: z.string().default("es").describe("Document language (ISO 639-1 code)"),
  currency: z.string().default("ARS").describe("Currency code for prices (ISO 4217)"),
  priceInterpretationDefaults: z
    .object({
      includesTax: z
        .boolean()
        .describe("Whether prices include tax by default in this document"),
      priceUnit: z
        .enum(["per-pack", "per-unit", "per-kg", "per-liter", "variable"])
        .describe("Default price unit interpretation"),
    })
    .optional()
    .describe("Default rules for interpreting prices"),
  pages: z.array(PageMetadataSchema).describe("Metadata for each page"),
  sections: z.array(SectionMetadataSchema).optional().describe("Logical sections in the document"),
  globalRules: z
    .array(z.string())
    .optional()
    .describe("Global interpretation rules (e.g., 'all prices in USD', 'brands in bold')"),
  ambiguityNotes: z
    .array(z.string())
    .optional()
    .describe("Notes about ambiguous aspects that may need human review"),
});

export type DocumentMetadata = z.infer<typeof DocumentMetadataSchema>;

// ============================================================================
// Product Extraction Schemas
// ============================================================================

/**
 * Packaging information for a product
 * Extracted and normalized by the AI model
 */
export const PackagingInfoSchema = z.object({
  packagingType: z
    .enum(["bottle", "carton", "box", "bag", "crate", "unit", "unknown"])
    .describe("Type of packaging"),
  saleFormat: z
    .enum(["single", "multi-pack", "bulk", "variable"])
    .describe("How the product is sold"),
  unitsPerPack: z.number().int().min(1).optional().describe("Number of units in a multi-pack"),
  netQuantity: z.number().min(0.000001).describe("Net quantity of product"),
  netUnit: z
    .enum(["litro", "ml", "kg", "g", "unidad"])
    .describe("Unit of measure for net quantity"),
});

export type PackagingInfo = z.infer<typeof PackagingInfoSchema>;

/**
 * Price interpretation with confidence score
 * The AI model determines what the price represents
 */
export const PriceInterpretationSchema = z.object({
  amount: z.number().min(0.000001).describe("Price amount in document currency"),
  type: z
    .enum(["per-pack", "per-unit", "per-kg", "per-liter", "wholesale", "retail", "unknown"])
    .describe("What this price represents"),
  confidence: z.number().min(0).max(1).describe("Confidence score for price interpretation (0-1)"),
});

export type PriceInterpretation = z.infer<typeof PriceInterpretationSchema>;

/**
 * Product extraction status for workflow tracking
 */
export const ProductExtractionStatus = z.enum([
  "draft",
  "needs-review",
  "approved",
  "rejected",
  "processed",
]);

export type ProductExtractionStatus = z.infer<typeof ProductExtractionStatus>;

/**
 * Single product extracted from document chunk
 * This is the core data structure for the hybrid pipeline
 */
export const ProductExtractionSchema = z.object({
  // Raw input
  rawText: z.string().describe("Original text from document for this product"),

  // Normalized fields (AI-interpreted)
  canonicalName: z.string().describe("Normalized product name (e.g., 'Leche Entera')"),
  brand: z.string().describe("Brand name (normalized to lowercase, no spaces)"),
  category: z.string().describe("Product category (e.g., 'lacteos')"),
  subcategory: z.string().optional().describe("Product subcategory (e.g., 'leches')"),

  // Packaging and pricing
  packaging: PackagingInfoSchema.optional().describe("Packaging information"),
  price: PriceInterpretationSchema.describe("Price interpretation with confidence"),

  // Classification
  tags: z.array(z.string()).describe("Tags for tree navigation (e.g., ['lacteos', 'leches', 'serenisima'])"),

  // Quality metrics
  confidence: z.number().min(0).max(1).describe("Overall extraction confidence (0-1)"),
  ambiguityNotes: z.array(z.string()).optional().describe("Notes about ambiguous aspects"),

  // Workflow status
  status: ProductExtractionStatus.describe("Current status in extraction workflow"),
});

export type ProductExtraction = z.infer<typeof ProductExtractionSchema>;

/**
 * Response schema for chunk processing
 * Contains multiple product extractions with context
 */
export const ProductChunkResponseSchema = z.object({
  items: z.array(ProductExtractionSchema).describe("Products extracted from this chunk"),
  chunkContext: z
    .object({
      chunkIndex: z.number().int().nonnegative().describe("Chunk number in sequence"),
      totalChunks: z.number().int().min(1).describe("Total number of chunks"),
      pageRange: z
        .tuple([z.number().int().min(1), z.number().int().min(1)])
        .describe("Page range for this chunk [start, end]"),
    })
    .describe("Context about this chunk's position in the document"),
});

export type ProductChunkResponse = z.infer<typeof ProductChunkResponseSchema>;

// ============================================================================
// JSON Schema Conversions for Gemini
// ============================================================================

/**
 * Convert Zod schemas to JSON Schema for Gemini's structured output
 * Gemini uses JSON Schema Draft 2020-12
 */

// Helper type for JSON Schema output
type JsonSchema = Record<string, unknown>;

export const DocumentMetadataJsonSchema: JsonSchema = zodToJsonSchema(
  DocumentMetadataSchema as any,
  {
    name: "DocumentMetadata",
    target: "openApi3",
  }
) as JsonSchema;

export const ProductExtractionJsonSchema: JsonSchema = zodToJsonSchema(
  ProductExtractionSchema as any,
  {
    name: "ProductExtraction",
    target: "openApi3",
  }
) as JsonSchema;

export const ProductChunkResponseJsonSchema: JsonSchema = zodToJsonSchema(
  ProductChunkResponseSchema as any,
  {
    name: "ProductChunkResponse",
    target: "openApi3",
  }
) as JsonSchema;

// Export with expected names for ingest.ts
export const DOCUMENT_METADATA_JSON_SCHEMA = DocumentMetadataJsonSchema;
export const PRODUCT_EXTRACTION_JSON_SCHEMA = ProductExtractionJsonSchema;
export const PRODUCT_CHUNK_JSON_SCHEMA = ProductChunkResponseJsonSchema;

// ============================================================================
// Prompts for AI Models
// ============================================================================

export const DOCUMENT_METADATA_PROMPT = `
You are analyzing a PDF document for a B2B catalog ingestion system.

Your task is to extract comprehensive metadata about this document including:
1. Document type (price-list, catalog, invoice, order-form)
2. Language and currency
3. Page-by-page layout analysis (tables, lists, mixed)
4. Section structure (categories, chapters)
5. Table detection with row counts
6. Column headers in tables
7. Global interpretation rules
8. Any ambiguous aspects that need human review

Focus on accuracy. If unsure about something, mark it in ambiguityNotes.

Return JSON following the provided schema.
`;

export const PRODUCT_EXTRACTION_PROMPT = (metadata: any, chunk: any) => `
You are extracting products from a B2B catalog document.

DOCUMENT CONTEXT:
- Type: ${metadata.documentType}
- Language: ${metadata.language}
- Currency: ${metadata.currency}

${metadata.globalRules ? `Global rules:\n${metadata.globalRules.join('\n')}\n` : ''}

${chunk.sectionTitle ? `Section: ${chunk.sectionTitle}\n` : ''}

TASK: Extract products from pages ${chunk.pageRange.start}-${chunk.pageRange.end}.

For each product, provide:
- Raw text from document
- Normalized name (e.g., "Leche Entera")
- Brand (normalized lowercase)
- Category
- Tags for navigation (e.g., ["lacteos", "leches", "serenisima"])
- Packaging info (type, format, quantities)
- Price with type (per-pack, per-unit, etc.)

CRITICAL:
- If confidence < 0.7 or information is ambiguous, set status: "needs-review"
- If unclear about packaging, sale format, or price type, mark as needs-review
- Estimate confidence honestly (0.5-1.0 range)

Expected product count: ~${chunk.estimatedItems}

Return JSON following the provided schema.
`;

// ============================================================================
// Export All
// ============================================================================

export default {
  // Document-level schemas
  DocumentMetadataSchema,
  PageMetadataSchema,
  SectionMetadataSchema,

  // Product-level schemas
  ProductExtractionSchema,
  ProductChunkResponseSchema,
  PackagingInfoSchema,
  PriceInterpretationSchema,

  // Status enum
  ProductExtractionStatus,

  // JSON schemas for Gemini
  DocumentMetadataJsonSchema,
  ProductExtractionJsonSchema,
  ProductChunkResponseJsonSchema,
};
